#!/bin/sh -e

# Remove uneeded udev rule
sed -i '/^udev/,$ s/^/#/' util/meson.build

mkdir build
cd build

meson \
    --prefix=/usr ..

ninja
DESTDIR="$1" ninja install

# Remove all info files.
rm -rf "$1/usr/share/info"

# Remove docs.
rm -rf "$1/usr/share/doc"
