#!/bin/sh -e

./configure \
    --prefix=/usr \
    --disable-static \
    --disable-gpg-test

make
make DESTDIR="$1" install

# Remove all info files.
rm -rf "$1/usr/share/info"

# Remove docs.
rm -rf "$1/usr/share/doc"
