#!/bin/sh -e

# gcc 10 fix
sed -i '/The name/,+2 d' src/global.c

./configure \
    --prefix=/usr \
    --with-rmt=/usr/libexec/rmt

make
make DESTDIR="$1" install

# Remove all info files.
rm -rf "$1/usr/share/info"

# Remove docs.
rm -rf "$1/usr/share/doc"

