#!/bin/sh

ar x google-chrome-beta_current_amd64.deb
tar -xvf data.tar.xz

# Removing useless stuff.
rm -rf opt/google/chrome-beta/cron/
rm -rf usr/share/gnome-control-center/
rm -rf usr/share/doc/

cp -av opt "$1" 
cp -av usr "$1"

chmod 4755 "$1/opt/google/chrome-beta/chrome-sandbox"

echo "Fixing icons"
for i in 16x16 24x24 32x32 48x48 64x64 128x128 256x256; do
install -v -Dm644 opt/google/chrome-beta/product_logo_${i/x*}_beta.png \
"$1"/usr/share/icons/hicolor/$i/apps/google-chrome-beta.png
done
