#!/bin/sh -e

sed -i -e 's|-Werror||g' -e 's|.*common-agent/etc/config/Makefile.*||' configure.ac
#mkdir -p common-agent/etc/config
autoreconf -vi

./configure --prefix=/usr \
--sbindir=/usr/bin \
--without-xmlsecurity \
--without-dnet \
--without-icu \
--without-dncp

make
make DESTDIR="$1" install

# Remove all info files.
rm -rf "$1/usr/share/info"

# Remove docs.
rm -rf "$1/usr/share/doc"
