#!/bin/sh -e

mkdir build
cd build

meson \
    --prefix=/usr \
    -Dlibproxy=disabled ..

ninja
DESTDIR="$1" ninja install

# Remove all info files.
rm -rf "$1/usr/share/info"

# Remove docs.
rm -rf "$1/usr/share/doc"
