#!/bin/sh -e

sed -i '/MV.*old/d' Makefile.in
sed -i '/{OLDSUFF}/c:' support/shlib-install

./configure --prefix=/usr    \
    --disable-static

make SHLIB_LIBS="-L/tools/lib -lncursesw"
make SHLIB_LIBS="-L/tools/lib -lncursesw" DESTDIR="$1" install


# Remove all info files.
rm -rf "$1/usr/share/info/"
