#!/bin/bash
TOGGLE=/tmp/.toggle-pad

if [ ! -e $TOGGLE ]; then
	touch $TOGGLE
	xinput set-int-prop "pointer:SIPODEV USB Composite Device" 141 8 0
else
	rm $TOGGLE
	xinput set-int-prop "pointer:SIPODEV USB Composite Device" 141 8 1
fi
