#!/bin/sh -e

export pkgver=1.79.2

patch -Np1 -i docbook-xsl-nons-1.79.2-stack_fix-1.patch

install -v -m755 -d "$1/usr/share/xml/docbook/xsl-stylesheets-nons-${pkgver}"

cp -v -R VERSION common eclipse epub extensions fo highlighting html \
    htmlhelp images javahelp lib manpages params profiling \
    roundtrip slides template tests tools webhelp website \
    xhtml xhtml-1_1 \
    "$1/usr/share/xml/docbook/xsl-stylesheets-nons-${pkgver}"

ln -s VERSION "$1/usr/share/xml/docbook/xsl-stylesheets-nons-${pkgver}/VERSION.xsl"

install -v -m644 -D README \
    $1/usr/share/doc/docbook-xsl-nons-${pkgver}/README.txt

install -v -m644    RELEASE-NOTES* NEWS* \
    $1/usr/share/doc/docbook-xsl-nons-${pkgver}

