#!/bin/sh -e

./configure \
    --prefix=/usr \
    --disable-static \
    --exec-prefix=/

make
make DESTDIR="$1" install

# Remove all info files.
rm -rf "$1/usr/share/info"

# Remove docs.
rm -rf "$1/usr/share/doc"

# Remove usless files
rm -rf "$1/etc/init.d"
rm -rf "$1/dev"
