#!/bin/sh

ln -sv /tools/bin/{cat,chmod,dd,echo,false,ln,ls,mkdir,pwd,rm,stty,touch} /usr/bin
ln -sv /tools/bin/{env,install,perl,printf}         /usr/bin
ln -sv /tools/lib/libgcc_s.so{,.1}                  /usr/lib
ln -sv /tools/lib/libstdc++.{a,so{,.6}}             /usr/lib

mkdir -pv /usr/lib/pkgconfig

for lib in blkid mount uuid fdisk
do
    ln -sv /tools/lib/lib$lib.so* /usr/lib
    sed 's|/tools|/usr|' /tools/lib/pkgconfig/${lib}.pc \
        > /usr/lib/pkgconfig/${lib}.pc
done
for incdir in blkid libmount uuid libfdisk
do
    ln -svf /tools/include/$incdir    /usr/include
done

mkdir -pv /tools/lib/locale
ln -sv /usr/lib/locale/locale-archive /tools/lib/locale
