#!/bin/sh -e

./configure --prefix=/usr                        \
            --sysconfdir=/etc                    \
            --disable-setuid                     \
            --enable-cache-owner=bin             \
            --with-browser=/usr/bin/links        \
            --with-vgrind=/usr/bin/vgrind        \
            --with-grap=/usr/bin/grap

make
make DESTDIR="$1" install

# Remove all info files.
rm -rf "$1/usr/share/info"

# Remove docs.
rm -rf "$1/usr/share/doc"
