#!/bin/sh -e

./configure --prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --enable-user-session \
    --disable-doxygen-docs \
    --disable-xml-docs \
    --disable-static \
    --with-console-auth-dir=/run/console \
    --with-system-pid-file=/run/dbus/pid \
    --with-system-socket=/run/dbus/system_bus_socket

make
make DESTDIR="$1" install

# Remove all info files.
rm -rf "$1/usr/share/info"

# Remove docs.
rm -rf "$1/usr/share/doc"

chown -v root:messagebus "$1/usr/libexec/dbus-daemon-launch-helper"
chmod -v      4750       "$1/usr/libexec/dbus-daemon-launch-helper"

mkdir -pv "$1/etc/dbus-1/"

install -m644 session-local.conf "$1/etc/dbus-1/"
