#!/bin/sh -e

# Use lib not lib64 by default.
sed -i '/m64=/s/lib64/lib/' gcc/gcc/config/i386/t-linux64
sed -i 's/lib64/lib/' gcc/gcc/config/i386/linux64.h

# Build must happen outside of gcc source.
mkdir -p gcc-build
cd gcc-build

    ../gcc/configure \
    --prefix=/usr \
    --disable-multilib \
    --disable-werror \
    --enable-checking=release \
    --mandir=/usr/share/man \
    --infodir=/usr/share/info \
    --with-system-zlib \
    --enable-languages=c,c++

make
make DESTDIR="$1" install

# Enable LTO

install -v -dm755 "$1/usr/lib/bfd-plugins"
ln -sfv ../../libexec/gcc/$(gcc -dumpmachine)/10.1.0/liblto_plugin.so \
        "$1/usr/lib/bfd-plugins/"

# Save 35MB.
find "$1" -name libgtkpeer.a  -delete
find "$1" -name libgjsmalsa.a -delete
find "$1" -name libgij.a      -delete

# Some legacy programs will expect cc
ln -s gcc "$1/usr/bin/cc"

# POSIX compliance.
install -Dm755 ../c99 "$1/usr/bin/c99"
