#!/bin/sh -e

mkdir build
cd build

meson \
    --prefix=/usr \
    -Drpm=false \
    -Dman=false \
    -Dintrospection=false \
    -Dstemmer=false \
    -Dgtk-doc=false \
    ..

ninja
DESTDIR="$1" ninja install
